[
"Cigarettes Stuck Together",
"Reparation",
"Cigt Stuck To Foil",
"Vibration In E-Cigarette",
"Battery LED Does Not Illuminate During Use",
"Used Battery Hard To Draw",
"Used Battery Too Easy To Draw",
"Personal Charging Case Does Not Charge Battery",
"Personal Charging Case Loose Wires",
"Cracking or Popping Noise",
"Battery No Vapor Delivery - LED Off",
"Battery No Vapor Delivery - LED On",
"Battery No Vapor Delivery - LED Flashes 2 Times",
"Battery No Vapor Delivery - LED Information Not Provided",
"Mold/Mildew",
"Ammonia",
"Almond/Nutty Smell *Special Handling*",
"E-Cigarette Breaks Too Easy",
"Battery LED Stays On",
"Loose Tobacco In Can/Pouches Intact",
"Battery Charge Depletes More Quickly After Multiple Recharges",
"Battery Charge Depletes More Quickly Than Previous Purchases",
"Battery LED Falls Off",
"Battery Missing Covering  (Label)",
"Battery Replacement Low Vapor Delivery",
"LED Cover Falls Off",
"New Battery Hard To Draw",
"New Battery Too Easy To Draw",
"Cartridge Hole Size Variation or Holes Covered By Flag",
"Home Circuit Problem When AC Adaptor Used",
"Battery Charges Too Slow",
"E- Cigarette No Vapor Delivery - Initial Use",
"Satisfaction Guarantee",
"Envelope Damage From Tax Stamp Application",
"Battery Damaged",
"Cartridge Damaged",
"Charger AC Damaged",
"Charger Car Damaged",
"Charger USB Damaged",
"Battery Appearance",
"Battery Cannot Connect To Cartridge",
"Battery Cannot Connect To Cartridge - Loose Connection",
"Battery Cannot Connect To Charger - Loose Connection",
"Battery Cannot Connect To Charger",
"Battery Will Not Charge",
"Battery Will Not Charge - USB LED - GREEN",
"Battery Will Not Charge - USB LED - RED",
"Battery Charge Depletes More Quickly Than Expected",
"Cartridge Appearance",
"Cartridge Cannot Remove From Battery",
"Cartridge Label Peeling",
"Cartridge Mouthpiece Damage",
"Cartridge No Vapor Delivery - LED Flashes 2 Times",
"Cartridge No Vapor Delivery - LED Information Not Provided",
"Cartridge No Vapor Delivery - LED Off",
"Cartridge No Vapor Delivery - LED On",
"Cartridge Parts Loose",
"Cartridge Replacement Does Not Connect To Battery",
"Cartridge Replacement Does Not Connect To Battery - Loose Connection",
"Cartridge Replacement Hard To Draw",
"Cartridge Replacement Too Easy To Draw",
"Cartridge Low Vapor Delivery - LED Information Not Provided",
"Cartridge Low Vapor Delivery - LED Off",
"Cartridge Low Vapor Delivery - LED On",
"Cartridge Did Not Last Long Enough",
"Cartridge Did Not Last As Long As Previous Purchases",
"Charger AC Appearance",
"Charger AC Battery Does Not Charge - AC LED Off",
"Charger AC Battery Does Not Charge - AC LED On / USB LED Off",
"Charger AC Battery Does Not Charge - AC LED On / USB LED On",
"Charger AC Battery Does Not Charge - AC LED Information Not Provided",
"Charger AC Parts Loose",
"Charger Car  Battery Does Not Charge - LED Off",
"Charger Car  Battery Does Not Charge - LED On / USB LED Off",
"Charger Car  Battery Does Not Charge - LED On / USB LED On",
"Charger Car  Battery Does Not Charge - LED Information Not Provided",
"Charger Car Appearance",
"Charger Car Parts Loose",
"Charger USB Appearance",
"Charger USB Battery Does Not Charge - LED Off",
"Charger USB Battery Does Not Charge - LED On E-Cig LED Off",
"Charger USB Battery Does Not Charge - No LED On USB / E-Cig LED Off",
"Charger USB Battery Does Not Charge - No LED On USB / E-Cig LED On",
"Charger USB Battery Does Not Charge - Works For Some Devices But Not Others",
"Charger USB Battery Does Not Charge - LED On / E-Cig LED On",
"Charger USB Battery Does Not Charge - LED Information Not Provided",
"Charger USB Parts Loose",
"Blister Pack Damaged",
"Blister Pack Opened",
"Box Appearance",
"Box Damaged",
"Box Slit Open",
"Box Security Tape Not Secured",
"Cartridge Cap Damaged",
"Case Label Damaged",
"Case Label Missing",
"Case Tape Damaged",
"Case Tape Missing",
"Case Tape Not Sealed",
"Communication Kit Damaged",
"Foam Packing Blocks Damaged",
"General Packaging",
"Label Damaged",
"Label Illegible",
"Tube Damaged",
"Tube Cap Damaged",
"E-Cigarette Other",
"General Complaint Filter/Plug",
"Carton Code Illegible",
"Carton Code Missing",
"Ash Fall Off",
"General Complaint Cigarette",
"Air Leak",
"Filter Falls Off",
"Onsert Quality",
"Onsert Missing",
"Wet Rod",
"Extra Tipping",
"Coal Drop Off",
"Cigt Exploded/Flared Up",
"Filter Flare Up",
"Self-Extinguishes",
"Cigt Popped/Sparked",
"Hard To Put Out",
"General Information",
"Hard To Light",
"Hard To Draw",
"Uneven Burning",
"Does Not Self Extinguish",
"Discomfort",
"Incompletely Filled Pouch",
"Pouch Empty - Single Pouch",
"Pouch Chain - Single Pouch",
"Pouch Chain",
"Pouch Empty - Multiple Pouches",
"Pouch Open Long Seam",
"Pouch End Seal Quality",
"Pouch Open End Seal",
"Pouch Hole",
"Seal Quality",
"Flavor Strip Position",
"Pouch Seal",
"Incorrect Cigarette In Pack",
"Improper Fold Carton",
"Carton Missing Kit",
"Carton Appearance",
"Carton Slit Open",
"Carton Tear/Hole",
"Carton Supplier Printing Quality",
"Pack Missing From Carton",
"Carton Missing Adhesive/Open",
"Carton Damaged",
"Carton Mashed",
"Case Printing Supplier",
"Cartons Missing From Case",
"Case Not Labeled Correctly / Legible",
"Carton Missing From Case",
"Case Slit",
"Case Not Sealed",
"Case Damaged",
"Case Mashed",
"Too Moist",
"Improper Cut",
"Factory Beetle Infestation",
"Beetle Occurrence",
"Ash Control",
"Tipping Mashed",
"Warning Notice Legible",
"Supplier Print / Artwork",
"Tear Slit Hole Case",
"Field Beetle Infestation",
"Beetle Infestation",
"Beetles In Pack",
"Beetle Occurrence Product Over 1 Year Old",
"Broken/ Bent Cigar",
"Burning Too Fast",
"Burning Too Slow",
"Cigar Hole",
"Cigar Holes Near Mouthpiece",
"Tobacco Appearance",
"Cigar Appearance",
"Hard To Keep Burning",
"Incompletely Filled",
"Insects In Pack",
"Insect Infestation",
"Missing / Light  Print",
"Stem Content",
"Case Adhesion",
"Long/Short Cigarette",
"Case Appearance General",
"Case Damage",
"Mixed/Pack And Case Date Code Mismatch",
"All/Date Codes Not Provided",
"All/Pack And Case Date Code Match",
"All/Pack And Case Date Code Mismatch",
"Mixed/Date Codes Not Provided",
"Mixed/Pack And Case Date Code Match",
"Missing Cigars From Case",
"Mashed Case",
"Missing Carton From Case",
"NPRM In/On Tipping",
"Z{Ats}Ntrm Blood",
"NPRM In/On Plug",
"Improper Fold Film",
"Loose Film",
"Upside Down Label",
"Excess Adhesion",
"Missing Cigarette From Pack",
"Empty Pack",
"Excessive Adhesive Closure/Stamp",
"Improper Fold Foil",
"Cigts Exposed/Cause Unknown",
"Missing Pull Tab",
"Excessive Adhesive Label/Blank",
"Foil Adhesion",
"Innerframe Adhesion",
"Closure/Stamp Adhesion",
"Missing Closure/Stamp",
"Missing Foil",
"Missing Innerframe",
"General Complaint Carton",
"Non Pmusa Brand",
"Incorrect Tear Tape",
"Closure/Stamp Position",
"Improper Fold Soft Pack",
"Coupon Damaged",
"Wrinkled Rod",
"Mashed Rod",
"Torn Rod",
"Torn End",
"Packaging / Metal",
"Missing Pack From Carton",
"Missing Envelope From Carton",
"General Complaint Print",
"General Complaint Rod",
"General Complaint Tipping",
"Long/Short Plug",
"Wrinkled Tipping",
"Long/Short Tipping",
"Missing Filter (plug and tipping paper)",
"Missing Plug",
"Missing Rod",
"Promotional Pack Appearance",
"Promotional Pack Construction",
"Pack Damage From Tax Stamp Application",
"General Complaint Closure/Stamp",
"General Complaint Film",
"Promotional Package Quality General",
"General Complaint Foil",
"General Complaint Innerframe",
"Tax Stamp Quality Issue",
"Pilferage",
"Miscellaneous Distribution Quality",
"Duty Free Product Sent To Domestic Market",
"Product Handling Damage Distribution",
"Distribution",
"General Complaint Label/Blank",
"Innerframe Position",
"Hard pack Will Not Open - Miter Stuck",
"Hard Pack Top Rips When Opening",
"Pack Will Not Close",
"Extra Product Material In Carton",
"Tipping To Plug Adhesion",
"Tipping Turned Up",
"Stem",
"Rod Hole",
"Print Hole",
"Stem Hole",
"Past Sell By Date",
"Smeared Tipping",
"Rolling Papers Burn Too Fast",
"Rolling Papers Do Not Stay Sealed",
"Extra Carton Blank",
"Extra Cigarette Material In Carton",
"Extra Packaging Material In Carton",
"Tipping Turned Up/Under",
"Too Much Pz",
"NPRM In Filler/Unknown",
"NPRM In Filler/Metal",
"Missing Cigars From Pack",
"Pack Adhesion",
"Pack Adhesion (Hard/Soft)",
"Tear/ Hole Pack",
"Open Unsealed Film",
"Miscellaneous Distribution",
"Missing Cigars From Display Box",
"NPRM In Filler/Wood",
"NPRM In Filler/Plastic",
"NPRM On Rod",
"Z{Ats}Ntrm Polymer - Adhesive",
"Tear Slit Hole Film",
"Z{Ats}Ntrm Unknown Source",
"Product Over Freshness Date",
"Aroma Too Mild",
"Aroma Too Strong",
"Aroma Unpleasant",
"Smells Bad Before Lighting",
"Unpleasant",
"Too Strong",
"Too Mild",
"Cigar Smells Bad Before Lighting",
"Too Easy To Draw",
"Too Hard To Draw",
"Too Much Variation",
"Too Dry",
"Too Much Moisture From Burn / Gurgle In Bowl / Wet Heal",
"No Presenting Cause Cigt Appearance",
"Display Box Adhesion",
"Empty Display Box",
"Tear / Hole Display Box",
"Distribution Case Damage",
"Mashed Display Box",
"Carton Hole",
"Carton Tear",
"Damaged Carton",
"Mashed Carton",
"Carton Mashed/Crushed",
"Soft Plug",
"Wrapper Open Seal",
"Band Missing",
"Loose Ends Tobacco",
"Missing Tip",
"Missing Filter",
"Open Seam / Unraveling",
"Tip Falls Off",
"Tip Falls Off No Adhesive",
"Tip Loose",
"Filter Falls Off No Adhesive",
"Tobacco Clumps",
"Too Much Adhesive Around Tip",
"Torn Wrapper",
"Wrapper Missing",
"Chalky Mouth",
"Hot Burning / Scorched Tongue",
"Does Not Form Plumes",
"Too Little Volume",
"Too Much Volume",
"Volume Too Little",
"Volume Too Much",
"Off Taste",
"Broken",
"Open Seam",
"Too Little Flavor In Tip",
"Tear Tape Missing",
"Tear Tape Break",
"Scratched / Burr",
"Too Much Flavor In Tip",
"Sizzling / Popping",
"Tobacco Dust Too Much",
"Brittle",
"Does Not Pack Well",
"Sticky",
"Does Not Build Nice Cake",
"Excess Residue /Pipe Goops Up",
"Over Aromatizes Your Pipe",
"Tear Slit Hole Packet",
"Print Position - High/Low/Circumference",
"Mashed Packet",
"Incompletely Filled Packet (Missing Pipe Tobacco)",
"Empty Packet",
"Open Packet",
"Missing Packets of Pipe Tobacco",
"Bag Seal",
"Tear Slit Hole Bag",
"Incompletely Filled Bag (Missing Pipe Tobacco)",
"Empty Bag",
"Bag Rips When Opened",
"Can Seal",
"Tear Slit Hole Can",
"Rod Discoloration",
"Mashed Can",
"Empty Can",
"Incompletely Filled Can (Missing Pipe Tobacco)",
"Missing Pipe Tobaccos From Case",
"Rod Filter Space",
"Void End",
"Incompletely Filled Rod",
"Loose End",
"Incompletely Filled Rod No Presenting",
"Scattered Charcoal In Plug",
"Heath Effects",
"Skewed Tipping",
"Cut Finger On Lid",
"Cut Lip",
"Nprm / Glass",
"Nprm / Metal",
"Nprm / Plastic",
"Wood",
"Dizziness",
"Headache",
"Nausea/Sick To Stomach",
"Can/Jar/Pack Empty",
"Label Taped On",
"Leaking Pouch",
"Warning Notice Missing/Illegible",
"Pouch End/Short Seam Open - Multiple Pouches",
"Pouch Side/Long Seam Open - Multiple Pouches",
"Pouch Opens During Use - Multiple Pouches",
"PouchTear/Slit/Hole - Multiple Pouches",
"Pouch Leaking No Location Identified - Multiple Pouches",
"Pouch Side/Long Seam Open - Single Pouch",
"Pouch Opens During Use - Single Pouch",
"PouchTear/Slit/Hole - Single Pouch",
"Pouch Leaking No Location Identified - Single Pouch",
"Lid Won'T Come Off",
"Loose Label",
"Pouch End/Short Seam Open - Single Pouch",
"Loose Lid",
"No Wax",
"Partial Wax",
"Smeared Print",
"Smeared Rod",
"Too Big",
"Too Small",
"Pouch Too Big - Multiple Pouches",
"Pouch Too Small - Multiple Pouches",
"Pouch Too Big - Single Pouch",
"Pouch Too Small - Single Pouch",
"Pouch Stuck In Lid (Wick)",
"Rusty",
"Gritty",
"Cut/Grain Size",
"Dry",
"Strong",
"Weak",
"No Flavor",
"Wax",
"Insect",
"Chemical",
"Bad",
"Biological - Mold/Mildew",
"Taste",
"Too Harsh",
"Too Little Flavor",
"Odor Before Lighting",
"Taste/Off Taste",
"Odor After Lighting",
"Aftertaste Unpleasant",
"Stale",
"Blend Contents",
"Alleged Physical Effect Only",
"Harshness Lacking",
"Odor",
"No Presenting Cause",
"Wet Pack",
"Taste/New Packaging",
"Taste/Too Little Menthol",
"Taste/Too Much Menthol",
"Menthol In Non-Menthol Brand",
"Too Little Menthol",
"Taste - Mentions Change In Packaging Or Product Graphics",
"Taste - Product Past Do Not Use After Date",
"Taste/Odor/Stale",
"Taste Burnt/Metallic/Rancid",
"Carton Overwrap Side To Side Registra",
"Can Falling Apart",
"Subjective",
"Flavor Delivery Inconsistent",
"Chewing (Too Hard)",
"Chewing (Too Soft)",
"Product Hole",
"Product Too Small",
"Product Too Large",
"Empty Display Carton",
"Packaging Quality",
"Product Discoloration",
"Display Carton Adhesion",
"Product Breaks Apart After Chewing",
"Product Breaks Apart After Extended Use",
"Carton Graphics Supplier Ink Smear",
"Carton Appearance General",
"Carton Contains Opened Tubes",
"Carton Adhesion",
"Display Carton Notch Out Perforation Missing / Not Working",
"Tear / Hole Display Carton",
"Missing Verve From Display Carton",
"Mashed Display Carton",
"All / Mismatch Product And Carton Date Codes",
"All / Match Product And Carton Date Codes",
"All / Date Codes Not Provided",
"Mixed / Match Product And Carton Date Codes",
"Mixed / Date Codes Not Provided",
"Mixed / Mismatch Product And Carton Date Codes",
"Missing Tube From Carton",
"Flavor Material",
"Fabric/Cloth",
"Glue",
"String",
"Other",
"Biological - Blood",
"Biological - Finger Nail",
"Biological - General",
"Biological - Hair",
"Biological - Plant Matter",
"Biological - Wood",
"Dirt/Sand/Stone/Rock",
"Liquid Unknown",
"Paper / Cardboard",
"Powder",
"Powder White  Replacement *Special H*",
"Case Damage General",
"Product Quality",
"Pm Promotional Item",
"Taste/Upon Relighting",
"Taste/Too Little Flavor",
"Taste/Too Much Flavor",
"Too Much Flavor",
"Inq/ Questions Additives",
"Different",
"Sour",
"Sweet",
"Ashy Taste End Of Bowl",
"Blend Not Right Too Little Leaf Component",
"Blend Not Right Too Much Leaf Component",
"Harshness Too Much",
"Sour Finish / Bitter",
"Pack Film Appearance",
"Packet Appearance",
"Packet Function",
"Bag Appearance",
"Bag Function",
"Tip Appearance",
"Tear Tape Appearance",
"Tear Tape Function",
"Can Appearance",
"Can Function",
"Pack Appearance",
"General",
"Pack Function",
"Display Carton Function",
"Display Carton Appearance",
"Case Appearance",
"Band Appearance",
"Band Film Opening",
"Display Box Appearance",
"Display Box Function",
"Pouch Appearance",
"Pouch Function",
"None",
"Sweetness Not Enough",
"Sweetness Too Much",
"Too Nutty Flavor",
"Too Sweet",
"Product Over 1 Yr Old",
"Product Purchased After - Do Not Use After Date",
"Product Too Close To - Do Not Use After Date",
"Product Over Do Not Use After Date",
"Medical Advice",
"Broken Cigarette",
"Plug Capsule Broken/Leaking",
"Plug Capsule Multiple Capsules In Plug",
"Plug Capsule Registration - Cut through Capsule",
"Plug Capsule Too Hard To Break",
"Plug Capsule Breaks Too Easy",
"Plug Capsule Leaking Through Tipping",
"Plug Capsule Leaking Through Plug End",
"1st Time Use",
"Other Known Substance",
"Cigar Tube Appearance",
"Cigar Tube Damaged",
"Cigar Tube Hard To Open",
"Missing Cigars From Cigar Tube",
"Cigar Tube Open/Unsealed",
"Filter Material",
"Load",
"Splice Tape",
"Cigar Tube Missing Stopper",
"Damaged Case",
"Case Hole",
"Case Tear",
"Case Code Missing/Illegible",
"Excessive Adhesive Cigarettes",
"Case Missing Seal Tape",
"All / Match Product And Roll Date Codes",
"All / Mismatch Product And Roll Date Codes",
"Mixed / Match Product And Roll Date Codes",
"Mixed / Mismatch Product And Roll Date Codes",
"Mixed / Product And Case Date Codes Mismatch",
"All / Product And Case Date Codes Match",
"All / Product And Case Date Codes Mismatch",
"Mixed / Product And Case Date Codes Match",
"Packs Slit Open",
"Promotional Pack - Empty",
"Missing Pack From Promotional Packing",
"Wet Case",
"Damaged Pack",
"Damaged Insert",
"Damaged Onsert",
"General Complaint Tear Tape",
"General Packaging Material (Supplier Related)",
"Missing Insert",
"Plug Discoloration",
"Tipping Paper Discoloration",
"Carton Contains Opened Packs",
"Pack Opened And Re-Sealed",
"Case Open",
"Extra Film",
"Tipping Tear",
"Tipping Hole",
"Tipping Open Seam - Exposed Plug",
"Closure/Stamp Tear",
"Closure/Stamp Hole",
"Film Tear",
"Film Hole",
"Foil Tear",
"Foil Hole",
"Innerframe Tear",
"Innerframe Hole",
"Label/Blank Tear",
"Label/Blank Hole",
"Hard Plug",
"Holes In Plug",
"Mashed Pack",
"Tear Slit Hole Pack",
"Missing Film",
"Pack Film Appearance General",
"Display Box Slit Open",
"Tear Tape Does Not Open Film",
"Missing Tear Tape",
"Tear Tape Position",
"Film Does Not Open",
"Cigar Pack Slit Open",
"Cigar Pack Opened And Re-Sealed",
"Pack Slit Open",
"Bag Slit Open",
"Pipe Tobacco Pack Opened And Re-Sealed",
"Pipe Tobacco Packet Opened And Re-Sealed",
"Pipe Tobacco Bag Opened And Re-Sealed",
"Pipe Tobacco Can Opened And Re-Sealed",
"Foil Discoloration",
"Taste General",
"Taste/Too Weak",
"Taste/Too Strong",
"Taste/Too Bad",
"Taste/Too Minty",
"Taste/Too Peppery",
"Taste/Too Salty",
"Taste/Too Sweet",
"Lid Strip Tears Off Pack",
"Lid Strip Will Not Re-Seal",
"Taste/Too Sour",
"Lid Strip Tear/Slit Hole",
"Formed Bottom Label Supplier Printing",
"Formed Bottom Damaged/Dented",
"Pack/Label Supplier Printing Quality",
"Pouch Missing From Tray Pack",
"Tray Pack Appearance General",
"Tray Pack Function General",
"Lid Strip Open/ Not Sealed",
"Lid Strip Will Not Open",
"Lid Strip Tears / Delaminates",
"Label Tear Slit Hole",
"Label Not Sealed",
"Label Will Not Open",
"Label Tears While Opening",
"Lidstrip Separates From Recloseable Label",
"Tray Pack Box Missing",
"Tray Pack Box Tear/Slit/Hole",
"Tray Pack Box Appearance General",
"Tray Pack Box Function General",
"Excessive Adhesive/ Boxes Stuck",
"Tray Pack Box Open/ Unsealed",
"Promotional Packing Tear/Slit/Hole",
"Promotional Packing Appearance General",
"Promotional Packing Function General",
"Opened/ Re-Sealed Product",
"Pouch Discoloration",
"General Complaint Packaging",
"Pouch Opens After Chewing",
"Pouch Opens After Extended Use",
"Missing Cigars From Promotional Pack",
"Carton General Packaging",
"Log Mashed/Crushed",
"Log General Packaging",
"Improper Fold Blank",
"Roll Missing Can",
"Pouch Missing From Promotional Pack",
"Angle Hair",
"Inverted Cigarette",
"Empty Can/Pouch/Jar",
"Pallet Incorrect Case On",
"Missing Case From Pallet",
"Case Missing Tape",
"Case Missing Carton",
"Case Opened/ Re-Sealed",
"Distribution Miscellaneous",
"Carton Missing Can",
"Pallet Missing Case",
"Case Missing Roll",
"Closure/Stamp Turned Back/Under",
"Can Damaged",
"Can Incompletely Filled",
"Can/Pack Empty",
"Can/Pack Incompletely Filled",
"Empty Pouch",
"Incompletely Filled Pouch (Missing Tobacco)",
"Mashed Pouch",
"Missing Loose Leaf Tobacco From Case",
"Pouch Damaged",
"Pouch Incompletely Filled",
"Pouch Open",
"Pouch Opened And Re-Sealed",
"Pouch Rips When Opened",
"Pouch Slit Open",
"Pouch Will Not Open",
"Tear Slit Hole Pouch",
"Cut Size",
"Carton Contains Opened Envelopes",
"Damaged Envelope",
"Envelope Top Rips When Opening",
"Envelope Will Not Close",
"Envelope Will Not Open",
"General Complaint Envelope",
"Envelope Hole",
"Improper Fold Envelope",
"Mashed Envelope",
"Envelope Opened And Re-Sealed",
"Empty Envelope",
"Missing Stick From Envelope",
"Envelope Slit Open",
"Excessive Adhesive Envelope",
"Envelopes Stuck Together",
"Envelope Tear",
"Sticks Inverted",
"Stick Broken",
"Stick Discoloration",
"Stick General Complaint",
"Stick Long/Short",
"Melted/Wrinkled Film",
"Open/Unsealed Film",
"Cigt Stuck To Envelope",
"Sticks Stuck",
"Tobacco Application Cracked",
"Tobacco Application Falls Off",
"Soft Stick",
"Tobacco Application Gritty",
"Tobacco Application Light",
"Packs Stuck Together",
"Tobacco Application Long/Short",
"Tobacco Application Missing",
"Tobacco Application Uneven",
"Tobacco Discoloration",
"Tobacco General Complaint",
"Tobacco Stem Content",
"Missing Warning Notice",
"Stuck Pull Tab",
"Hinge Lid Back Torn",
"Retention Cuts",
"Retailer Removed Coupon",
"Retailer Limiting Sales",
"No Out Of Stock Coupon",
"Factory Tour Inquiry",
"Prc Sent Coupons Expired",
"Hang Up",
"Call Terminated By Rep",
"Prank Call",
"Correspondence Incoherent",
"Discrimination",
"Retailer Out Of Stock",
"Retailer Does Not Stock",
"Ape - Long Term Use",
"Consumer For Regulation",
"Consumer Against Regulation",
"Extra Innerframe",
"Pkg Function",
"Price",
"Praise",
"Pkg Appearance",
"Like",
"Like Protects Product",
"Like Easy To Open",
"Like Keeps Closed",
"Like Removing Product",
"Like Graphic Design",
"Like Tamper Proof",
"Like Pack Material",
"Like Quantity In Pack",
"Like Size Of Pack",
"Dislike Doesn'T Protect",
"Dislike Hard To Open",
"Dislike Won'T Stay Closed",
"Dislike Removing Product",
"Dislike Graphic Design",
"Dislike Not Tamper Proof",
"Dislike Pack Material",
"Dislike Quantity In Pack",
"Dislike Size Of Pack",
"Dislike Packaging General",
"Dislike",
"Like Packaging General",
"Packaging",
"Protestor - Peta",
"Protestor - Truth .Com",
"Protestor - Other",
"Dislike Design General",
"Self -Extinguishment",
"Brand",
"Culture",
"Domestic Violence",
"Hunger",
"Youth Related",
"Ysp Miscellaneous Inquiries",
"Ysp Proposals/Ideas",
"Workplace Smoking",
"Want To Learn More Mailing",
"Quitter/Non-Smoker",
"Threatens To Quit",
"Current Legislation",
"Addiction",
"Support",
"Settlement",
"If You Want To Quit - Things To Know",
"Request Assistance",
"Quitting",
"Item Inquiry",
"Item Selection",
"Order Status",
"Request Item",
"Promotion",
"Upcs",
"Request",
"How To Store To Insure Freshness?",
"Requests For Samples",
"Shelf Life",
"Storage",
"Burn Rate",
"Parliament",
"Merit",
"Basic",
"Marlboro",
"Virginia Slims",
"B&H",
"Item Description",
"Website Information - Options",
"Website Information - Pmusa.Com",
"Website Information - Philipmorris.Com",
"Vendor/Supplier",
"Relocation To Richmond",
"Marijuana Legalization",
"Want To Be A Vendor",
"Investor Relations",
"Retail Customer Service",
"Sales Force",
"Corporate Phone Number",
"Media Affairs",
"Philip Morris Operating Company",
"Hr",
"Johnny",
"Pm History",
"Veni Vedi Veci",
"Buy Directly From Pm",
"Cant Find Discontinued Brand",
"Discontinued",
"Cant Find Specific Brand",
"Black Guide",
"When Does Test-Market Go National?",
"Where To Find Foreign  Brand In Us?",
"Where To Find Test-Market Brand?",
"Where To Find Us Brand In Foreign Market?",
"Internet Sales",
"Buy Directly From Jm",
"Limited Time/Qty.",
"Will It Replace Regular Marlboro?",
"Buy Directly From Usst",
"Product",
"Military Request",
"National Launch",
"Retailer",
"Biodegradable Filters",
"Nicotine Quantity",
"John Middleton Use Of Brand Descriptors",
"Adding Nicotine",
"Ingredients In Cigarettes - What Is  In Our Brands",
"Does It Contain Gluten",
"Ingredients",
"Nicotine Inquiry",
"Tar & Nicotine Inquiry",
"Kkk",
"Production Code",
"Chemical/Preservative Content",
"Enriched Flavor",
"Ingredients In Cigarettes - Whats In Our Brands",
"Nicotine Spiking",
"Philip Morris Use Of Brand Descriptors",
"Understanding Tar & Nicotine Numbers",
"New Packaging Information Request",
"Surgeon General Warnings",
"Pkg Appearance Praise",
"Pkg Function Praise",
"Pkg Function Dislike",
"Printers Marks",
"Pkg Appearance Dislike",
"Packaging/Film/Paper",
"Pouches",
"Flavor",
"Promotional Items",
"Order Damaged In Delivery",
"Item Not Selected",
"Wrong Address",
"Exceeds Catalog Estimated Delivery Date",
"No Mail Status",
"Mailroom Reject",
"Confirmed Up - Domestic Market",
"General Choice",
"Item Not Available",
"Item Defective/ Received Damaged",
"Extend Participation",
"Security Measures",
"New Store Contact",
"Sales Rep Complaint",
"Advertising",
"Fire Safety",
"Memoribilia",
"Tear/Slit/Hole Carton",
"Promise Not Fulfilled",
"Copy Of Ads",
"Request For Item Seen In Recent Ad",
"Wants To Be A Model In A Pm Ad",
"To Minors - Store Mentioned",
"Tax Stamp Incorrect Or Missing",
"Contrabrand/Counterfeit Cigarettes",
"Selling Complimentary Packs",
"Counterfeit",
"To Minors",
"Complimentary Product",
"Product With No Tax Stamp",
"Complimentary Cigarettes",
"Confirmed Up",
"Rude",
"Lack Of Follow-Up",
"Comments About Retailers",
"Comments From Retailers",
"Comments From Retailer",
"Comments About Retailer",
"Retail",
"Description",
"Sales Rep Phone Number",
"General Sales Force",
"All Issues",
"Requests Coupons",
"Requests Redemption",
"Damaged - Consumer Affairs Coupon",
"Expired - Consumer Affairs Coupon",
"Direct Marketing",
"Special Response",
"Financial",
"Address",
"Current Litigation",
"Website Information",
"Minor",
"Other Information Requests",
"Different Brands",
"Light Vs Regulars",
"Dislikes - 1st Time Use",
"Good/Better Than Competitive Brand",
"Good/Better Than Pm Brand",
"Praise - 1st Time Use",
"Worse Than Competitive Brand",
"Good/Better Than Other Jm Brand",
"Merit Family",
"Soft Vs Hard Pack",
"Switch To Lower Tar",
"Consumer Does Like",
"Dislike Taste General",
"Like Taste General",
"Dislike 1st Time Trying",
"Dislike Flavor Change",
"Like 1st Time Trying",
"Like Flavor Change",
"Pr/Price",
"Pr/Taste",
"72mm Cigarettes",
"General Inquire",
"Inq/Cant Find Product",
"Inq/Order Direct",
"Retailer Acceptance",
"Price Too High",
"Billboard",
"Youth Oriented Publication",
"Brand Ads",
"Ads In General",
"Issue Ads",
"Expired - Direct Marketing Coupon",
"Damaged - Direct Marketing Coupon",
"Objects To Value Received",
"Explanation",
"Non-Receipt",
"Against State/County Law",
"Taxes Included",
"Limits Number",
"Retailer Claiming Non-Payment By Cms",
"Wont Accept",
"Sexist Ads",
"Participation",
"Rules",
"Expiration Date",
"Upc Requirements/ Description",
"Wants To Participate - Under 21",
"Cant Participate - Ineligible",
"Schedule",
"Ticket Availability",
"Winner List Not Timely",
"Giveaways",
"Objects To Price Increases",
"Jm Facts",
"John Middleton History",
"Media Affairs Phone Number",
"Ysp Brochure",
"Request Brochure",
"Compensation",
"Financial Assistance",
"Non Compensation",
"Cigarette Smoking - Health Issues",
"Add Remove Or Change",
"Tar & Nicotine Numbers",
"Date Coding/How To Read It?",
"Comments From Youth",
"We Card",
"Are Materials Recyclable",
"Confirmation",
"Products",
"Litter",
"Onsert / Communication",
"Ideas/Suggestions",
"Light Weight Cigarettes",
"NPRM In Filler/String",
"How To Read Date Code",
"How To Read Mfg Trace Code",
"Product Name - Descriptors",
"Like Flavor String",
"Like Charcoal In Filter",
"Like Length 72mm",
"Like Tipping Design",
"Like Pouch Size",
"Like Filter Design",
"Like Design General",
"Request Free Product Or Samples",
"Request Free Product Or Samples Military",
"Request Financial Assistance",
"Consumer Wants To Purchase On Internet",
"Retailer Not Offering Discount",
"Can Not Find Specific Brand",
"Consumer Wants To Buy Direct",
"Discontinued Brand",
"Promotional Product",
"Test Market Product",
"Availability Military",
"Law Enforcement",
"Regulatory",
"What Is Verve?",
"How Do You Use Verve?",
"How Long Does Verve Last?",
"What Is Snus?",
"How Do You Use Snus?",
"How Long Does Snus Last?",
"General Inquiry",
"What Is an E-Cigarette?",
"How Do You Use E-Cigarette?",
"How Long Does E-Cigarette Last?",
"Tear/Slit/Hole Tipping",
"Tear/Slit/Hole Seam",
"Donation Request",
"Address/Phone Number",
"Employee",
"Brochure",
"Are Materials Biodegradable",
"Wait For Gide",
"Check Under 4 Weeks",
"Check 4 To 6  Weeks",
"Check Over 6 Weeks",
"Coupons Under 4 Weeks",
"Coupons 4 To 6  Weeks",
"Coupons Over 6 Weeks",
"Wait For Giid",
"Wait For Product Return",
"Status",
"Offer Support",
"Ideas And Suggestions",
"Against",
"Unsolicated Business Contacts",
"Consumer Not Understanding Price Discount",
"Little Recess",
"Contribution",
"Expired Coupons",
"Product Old At Retail",
"Recall - Retrieval",
"Coupons",
"Promo Coupons Expired",
"Event Participation",
"Banded Paper Legislation",
"FDA Regulation General",
"Age Limit",
"Counterfeit Product",
"Duty Free Or Export Product",
"Illegal Import Product",
"Missing Or Incorrect State Tax Stamp",
"Limits Use",
"Redemption",
"Retailer Requests Redemption",
"Sales Tax",
"Will Not Accept",
"Selling Complimentary Product",
"Selling To Minors",
"Facts - History",
"Media Contact",
"Non Altria Company Contact",
"Complimentary Product Sold",
"Bomb",
"Facility",
"General Dislikes",
"Product Design Likes",
"Packaging Design Dislikes",
"Cigarette Design Dislikes",
"Taste Likes",
"Taste Dislikes",
"Packaging Likes",
"General Likes",
"Emergency",
"Media",
"Mission Statement",
"Natural Treatment System",
"Graphics Change",
"Missing Charcoal",
"Missing Tipping Paper",
"Trademark Infringement",
"Inquiries/Remarks",
"Correspondence",
"Incorrect Tipping Paper",
"Tours",
"Contribution Request",
"Sponsorship",
"Offer Involvement/Support",
"Against Pm",
"Litigation",
"Sponsorship Request",
"Ad/Programs",
"Thank You",
"Comments",
"Complaint",
"Welcome To The Ranch",
"Outwit The West",
"Rewards",
"Marlboro Cowboy/Man",
"Suggestions",
"Ideas",
"Idea/Suggestions",
"Technology",
"Usage",
"New Issue",
"Onsert",
"Tipping Does Not Seal Joint",
"Wet Cigarette",
"Conference Invitation",
"Transportation",
"People",
"Allocations",
"Dislike Battery Life",
"Dislike Cartridge Life",
"Dislike Tipping Design",
"Dislike Pouch Size",
"Dislike Filter Design",
"Dislike Flavor String",
"Dislike Charcoal Filter",
"Dislike Length 72mm",
"Availability",
"Understanding Pricing/Discount",
"Not Offering Discount",
"Featured Business Or Person",
"Films",
"Blend 27",
"Call Terminated By Representative",
"Request For Brochure",
"Ingredients/T&N",
"Film",
"Is It Safer Than Smoking",
"Health Effects",
"Replacement",
"Free",
"Wants To Be A Model",
"Military",
"Difficulties",
"Website",
"Nicotine Numbers",
"Reading The Julian Date Code",
"Guarantee Freshness Date",
"Altria",
"Remarks",
"Courteous",
"Helpful",
"Knowledgeable",
"Why Are You Making This Product",
"Pm Facts",
"Elimination Of 5 Miles Catalog",
"Flavor Spots",
"Is It Biodegradable",
"Warning",
"Regulations",
"Excise Tax",
"Promotions",
"Unsolicited Business Contacts",
"Health Warnings",
"Second Hand Vapor",
"Promotional Contacts",
"Dislike Does Not Include Charger",
"Dislike Must Purchase All Chargers",
"Retailer Gave Incorrect Pack",
"How To Ask For Brand",
"Confusion At Retail",
"Can't Find Specific Brand",
"Praise/Remarks",
"Bothersome",
"Health Concerns",
"Second Hand Smoke",
"Health Concern",
"Privacy; Discrimination",
"Quota Grower",
"Return Call With Additonal Info",
"Vaping Restrictions",
"Smoking Restrictions",
"Bars",
"Housing",
"Public Places",
"Youth Access",
"Restaurants",
"Wrong Number / Hang-Up",
"Join Or Start Club",
"Alleged Tampering",
"Tar And Nicotine Content",
"Printed Filters",
"Miscellaneous",
"Recessed Filter",
"Peta",
"Refund",
"Surveys",
"Incoherent",
"Animal Testing",
"Threats",
"Phone Number",
"Operating Company Phone Number",
"Missing Item",
"Vendor Business/Deletion",
"Merchandising",
"Won'T Accept Coupons",
"Sales Service",
"Direct Mailing",
"Remove Name",
"Willing To Testify",
"Defective/Missing",
"Missing From Order",
"Missing Direct Mail/Retail Item",
"Tbd",
"Mailing List",
"Address Change",
"Add Name",
"Forwarded",
"Old Design/Graphics",
"No Presenting Cause Pack Appearance",
"Combined Filter Registration",
"Cigarette Paper Splice (Mfg)",
"Cigarette Paper Splice (Supplier)",
"Reprocess Reimbursement",
"Battery Label Peeling",
"Charger USB Battery Does Not Charge - LED On / E-Cig LED Off",
"Kit Do Not Use After Date  Missing/Illegible",
"Kit Trace Code Missing/Illegible",
"Feathered Seam",
"Wet Tipping/Filter",
"Uncut Filler",
"Incorrect Rod Paper",
"Nprm Pouch",
"Foil Bag Open",
"Foil Bag Bad Seal/Hole/Leak",
"Foil Bag Pull Tab Will Not Open",
"Foil Bag Pouch Shortage",
"Seam Quality",
"Light Weight",
"Incorrect Pouch In Pack",
"Slide Pack Window Will Not Open",
"Film Tear/Slit/Hole",
"Film Tear Tape Missing",
"Film Tear Tape Does Not Open",
"Film Tear Tape Tab Not Long Enough",
"Carton Production Code Missing",
"Carton Production Code Illegible",
"Overwrap Film Tear Tape Did Not Open",
"Ow Film Tear Tape Does Not Open Clean",
"Pack Shortage In Carton",
"Carton Tear/Slit/Hole",
"Open Flaps",
"Nprm In Can",
"Case Shortage Cartons",
"Plug Rods In Pack",
"Inverted Tipping Paper",
"Nprm On Can",
"Light/Nonuniform Print",
"General Complaint Mst Appearance",
"No Presenting Cause Mst Appearance",
"Non Product Related Material In Tobacco",
"Cut",
"Incorrect Cigar In Case",
"Z{Ats}Ntrm Biological",
"Case Code Missing / Illegible",
"Smeared Plug",
"Short Cut Foil",
"Smeared Film",
"Smeared Foil",
"Smeared Innerframe",
"Incorrect Pkg Material",
"Incorrect Rod/Filter Length - Design",
"Pleated Tipping",
"Coupon Missing",
"Wrong Brand In Case",
"Tipping Manufacturing Splice",
"Too Much Recess",
"J Pouch Display Carton Missing Or Illegible Warning Notice",
"J Pouch Display Carton Empty",
"J Pouch Display Carton Incomplete Count",
"J Pouch Display Carton Tear/Slit/Hole",
"J Pouch Display Carton Adhesion",
"Tipping Supplier Splice",
"Tipping Adhesion Tip To Tip",
"Tipping Adhesion Tip To Plug",
"J Pouch Overwrap Tear/Slit/Hole",
"J Pouch Overwrap Open Unsealed",
"J Pouch Overwrap Burned",
"J Pouch Overwrap General Appearance",
"J Pouch Sleeve General Appearance",
"J Pouch Sleeve Missing Or Illegible Warning Notice",
"J Pouch Sleeve Empty",
"Tipping Turned Under",
"Narrow Cut Tpg",
"Loose Plug",
"J Pouch Overwrap Missing",
"J Pouch Sleeve Tear/Slit/Hole",
"J Pouch Sleeve Adhesion",
"J Pouch Display Carton General Appearance",
"Canister Incompletely Filled",
"Canister Empty",
"Canister Disk Missing",
"Canister Disk General Appearance",
"Rolling Papers Missing",
"Canister Will Not Stay Shut",
"Canister Label Appearance",
"Canister Label Missing Or Illegible Warning Notice",
"Old On Shelf (Outdated)",
"Purchased Expired",
"Too Short Shelf Life",
"Canister General Appearance",
"Canister Bottom Broken",
"Canister Top Broken",
"Tipping Supplier Ink Smear",
"Insect Hole",
"Rolling Papers Overwrap Missing",
"Rolling Papers Shortage",
"Rolling Papers Tear/Slit/Hole",
"Rolling Papers Overwrap Tear/Slit/Hole",
"Rolling Papers Overwrap Open Unsealed",
"Rolling Papers Adhesive Missing",
"Filter Break",
"J Pouch Label Appearance",
"J Pouch Label Missing Or Illegible Warning Notice",
"Paper Break",
"Rolling Papers Overwrap Burned",
"Rolling Papers Overwrap General Appearance",
"Canister Overwrap Missing",
"Canister Overwrap Tear/Slit/Hole",
"Canister Overwrap Open Unsealed",
"Canister Overwrap Burned",
"Canister Overwrap General Appearance",
"J Pouch General Appearance",
"J Pouch Closure Tape Missing",
"J Pouch Closure Tape Torn",
"J Pouch Closure Tape Appearance",
"J Pouch Incompletely Filled",
"J Pouch Empty",
"J Pouch Closure Tape Will Not Adhere",
"NPRM In Filler/Fabric Material",
"Z{Ats}Ntrm Cellulose",
"Ntrm/Splice Tape",
"Nprm In Filler/Paper",
"NPRM In Filler/Rubber",
"Incorrect Cigar In Pack",
"Retailer Selling Complimentary Cigars",
"Moisture",
"Missing/Partial Ventilation Holes",
"Non Tobacco Related Material In Cigar",
"Non Tobacco Related Material On Cigar",
"Insect Infestation Factory Source",
"Insect Infestation Unknown Source",
"Insect Occurrence Product Over 1 Year Old",
"Scorched Carton",
"Tobacco Brittle",
"Tow In Filler",
"Packaging In Filler",
"Paper In Filler",
"Non Tobacco Related Material On Tip",
"Print Position - Circumferential",
"Tobacco Feel",
"Recessed Plug (Nrb)",
"Non Product Related Material On Bag",
"Soft Spots In Rod",
"Spot (Non-Flavor Related)",
"Label Splice",
"Shorts Under Tipping",
"Supplier Smeared Rod",
"No Label",
"Can/Jar/Pack Incompletely Filled",
"Liquid In Can",
"Metal",
"Mold",
"Glass",
"Sand",
"Stems",
"Stone/Rock",
"Straw (Cotton/Synthetic)",
"Plexiglass",
"Poly Fiber",
"Rubber",
"Paper",
"Plastic",
"Grass",
"Grease/Oil",
"Hair",
"Fingernail",
"Bolt/Screw",
"Brush Bristle",
"Tin",
"Incorrect Flavor",
"Tear/Slit/Hole Foil",
"Tear/Slit/Hole Innerframe",
"Tear/Slit/Hole Label/Blank",
"Tight Film",
"Improper Carton Blank",
"T/S/H Closure/Stamp",
"Ntrm In Carton",
"No Presenting Cause Carton Appearance",
"Missing Coupon",
"Not Moist Enough/Doesn'T Pack",
"Wet Carton",
"Smeared Carton",
"Wrong Brand In Carton",
"Wrong Brand In Case Mixed Cartons",
"Age Upon Receipt",
"Age",
"Bias Cut Tipping",
"Damaged Coupon",
"Incorrect Rod Print (Lettering Or Color)",
"Extra Cigarette In Pack",
"Missing Onsert",
"Printed Film Alignment / Registration",
"Printed Film Quality",
"Extra Foil",
"Extra Tear Tape",
"Cases Missing From Pallet",
"Missing Cases From Pallet",
"Nprm In /On Carton",
"Multiple Criticals",
"Wrinkled Foil",
"Improper U-Cut",
"Tear Tape Turned Back/Under",
"Short Tear Tape",
"Split/Cut Tear Tape",
"Tear Tape Adhesion",
"Different Flavor",
"Nprm In Pouch",
"Improper Carton Code",
"Registration (Superslims)",
"Open Locking Tabs (Superslims)",
"General Complaint Can",
"Nprm On Pouch",
"180 Degree Fold",
"Back Side Panel Bend",
"Missing Label/Blank",
"Missing Government Closure/Stamp",
"Inverted Closure/Stamp",
"Inverted Innerframe",
"Inverted Label/Blank",
"Inverted Tear Tape",
"Inverted Wrap",
"Label/Blank Turned Back/Under",
"Missing Pipe Tobacco Case From Pallet",
"Missing Pipe Tobacco From Case",
"Closure/Stamp Skewness",
"Innerframe Registration",
"Miter Side Panel Alignment",
"Tear Tape Alignment",
"Artwork Alignment",
"Carton Improper Fold Foil/Overwrap",
"NPRM In Pack",
"NPRM Under Film",
"Tear/Slit/Hole Film",
"Supplier Label/Blank Missing Print",
"Foil Embossing",
"Missing Print Label/Blank",
"Shorts Under Film",
"Label/Blank Supplier Ink Smear",
"Smeared Label/Blank",
"Metal -Tin",
"Plastic - General",
"Plastic - Plexiglas",
"Metal -Foil",
"Metal -General",
"Metal -Pin/Needle",
"Oil",
"Metal -Bolt/Screw/Staple",
"Kerosene",
"Grease",
"Fuel",
"Cleaning Agent",
"Plastic - Fishing Line",
"Metal -Wire",
"Plastic - Poly-Fiber",
"Paint",
"Incorrect Pouch In Promotional Pack",
"Roll Wrong Brand In / All Cans",
"Roll Wrong Brand In / Mixed Cans",
"Incorrect Cigar In Promotional Pack",
"Product Wrong In Can / Incorrect Flavor",
"Incorrect Pack Blank",
"Formed Bottom Label Missing",
"Incorrect Case Blank",
"Carton Wrong Brand In / Mixed Pouches",
"Carton Wrong Brand In / All Pouches",
"Wrong Brand In Promotional Pack",
"Crystals *Special Handling*",
"Fuel *Special Handling*",
"Explosive *Special Handling*",
"Illegal Substance *Special Handling*",
"Pellets *Special Handling*",
"Powder *Special Handling*",
"Unknown Substance *Special Handling*",
"No Lid",
"Plug Capsule Missing",
"Plug Capsule Wrong Flavor",
"Wrong Flavor",
"Product In Promotional Transfer Carton",
"Inverted Carton",
"Subjective Select",
"Product Quality Select",
"Product Wrong In Tube / Incorrect Flavor",
"Packaging Quality Select",
"Distribution Select",
"Incorrect Verve In Display Carton",
"Incorrect Pipe Tobacco In Can",
"Incorrect Pipe Tobacco In Pack",
"Incorrect Pipe Tobacco In Bag",
"Incorrect Pipe Tobacco In Packet",
"Incorrect Cigar In Display Box",
"Rod Print Different",
"Tipping Graphics Different",
"Wrong Brand On Tear Tape",
"Incorrect Carton Blank",
"Flavor Strip Missing",
"Label Missing",
"Battery Missing",
"Charger AC Missing",
"Charger Car Missing",
"Charger USB Missing",
"Charger Stand Missing",
"Personal Carrying Case Missing",
"Tube Missing",
"E- Cigarette Missing",
"Tube Cap Missing",
"Communication Kit Missing",
"Wrong E-Cigarette In Kit",
"Foam Packing Blocks Missing",
"Charger USB Too Hot",
"Box Security Tape Missing",
"Cartridge Missing",
"Cartridge Cap Missing",
"Charger AC Too Hot",
"Charger Car Too Hot",
"Battery Is Hot To The Touch *Do Not Return Battery*",
"Battery Is Hot To Touch LED Melted  *Do Not Return Battery*",
"Battery Is Leaking *Do Not Return Battery*",
"Cartridge Leaks E-Liquid * Do Not Return Product*",
"Cartridge Leaks E-Liquid",
"Cartridge Mouthpiece Missing",
"Charger USB NPRM",
"Cartridge Label Missing",
"E- Cigarette NPRM - Product Contact",
"Packaging NPRM - No Product Contact",
"Charger AC NPRM",
"Charger Car NPRM",
"Battery Label Missing",
"Computer Problem When USB Charger Connected",
"E- Cigarette Explodes or Flares Up",
"Electrical Shock",
"Missing Lot Number",
"Self-Activation Of Device",
"Cartridge Missing Covering (Label)",
"Vapor Too Hot But Cartridge Not Hot",
"Charger USB Sparks Or Smokes When Plugged Into Device",
"Cartridge Develops Condensation In It",
"Battery  LED Sparked",
"Battery LED Bulb Missing",
"NPRM Product Contact On Pouch",
"NPRM Packaging",
"NPRM Product Contact In Pouch",
"Consumer Alleges E-Cigarette Caught Fire",
"Cartridge Too Hot",
"NPRM Product Contact",
"Grease / Oil",
"Missing Do Not Use After Date",
"Sticks Wrong Flavor In Envelope",
"Envelope Incorrect Material",
"No Menthol In Menthol Brand",
"E-Cigarette Select Other",
"Different Product Identification On Side And Top Labels",
"Warning Notice And Product Identification Not Visible",
"Incorrect Stick Print (Lettering Or Color)",
]