/************************************************************************ 
Author: Randolf Suplito
Date: 06/24/2022
Description: This class holds constant variables
*************************************************************************/

public class ConstantClass {
    //RITM2248628
    public static final String CUSTOMERORCONSUMER_CONS = 'CONS';
    public static final String COUNTERFEITCODE_ZERO = '0';
    public static final String COUNTERFEITCODE_ONE = '1';
    public static final String COUNTERFEITCODE_TWO = '0';
    
    //RITM2322487
    public static final String RESPONSE_MESSAGE_CREATED = 'CREATED';
    public static final String INTEGRATIONLOG_NAME = 'Issue Adjustment';
    public static final String INTEGRATIONLOG_TYPE = 'Alorica';
    public static final String SUCCESS_TRUE = 'true';
    public static final String SUCCESS_FALSE = 'false';
    public static final String RESPONSE_MESSAGE_ISSUEIDNOTEXIST = 'Invalid IssueId';
    public static final String RESPONSE_MESSAGE_INVALIDREQID = 'Invalid Request Id';
    public static final String RESPONSE_MESSAGE_INVALIDADJCODE = 'Invalid Adjustment Code';
    public static final String ISSUEADJ_SUCCESS_STATUS = 'Success';
    
    //RITM2380477
    public static final String APIDATAFEED_TYPE_OUTBOUND = 'API Outbound';
    public static final String CUSTOMERTYPE_CALLOUT_NAME = 'Customer Type';
    public static final String USER_CALLOUT_NAME = 'User';
    public static final String STORETYPE_CALLOUT_NAME = 'Store Type';
    public static final String PRODUCTLINE_CALLOUT_NAME = 'Product Line';
    public static final String BRAND_CALLOUT_NAME = 'Brand Code';
    public static final String BRANDHIERARCHY_CALLOUT_NAME = 'Brand Hierarchy';
    public static final String ISSUEHIERARCHY_CALLOUT_NAME = 'Issue Hierarchy';
    public static final String SURVEY_CALLOUT_NAME = 'Survey Definition';
    public static final String SURVEYCONFIG_CALLOUT_NAME = 'Survey Config';
    public static final String QUESTION_CALLOUT_NAME = 'Survey Question';
    public static final String ANSWER_CALLOUT_NAME = 'Survey Answer';
    public static final String COUNTERFEITTRACECODE_CALLOUT_NAME = 'Counterfeit Trace Codes';
    
    //RITM2429522
    public static final String ISSUE_CALLOUT_NAME = 'Issue Feed';
}